export type Tool={slug:string;name:string;category:string;description:string;keywords:string[];intent:string[];related?:string[]};
export const tools:Tool[]=[
 {slug:'profit-calculator',related:['margin-calculator','break-even-calculator','pricing-calculator'],name:'Profit Calculator',category:'Business & Money',description:'Calculate revenue, costs, profit and profit margin.',keywords:['profit','money','margin','business'],intent:['losing money','not profitable','profit']},
 {slug:'roi-calculator',related:['roas-calculator','cac-calculator','profit-calculator'],name:'ROI (Return on Investment) Calculator',category:'Business & Money',description:'Measure return on an investment quickly.',keywords:['roi','return','investment'],intent:['investment','return']},
 {slug:'markup-calculator',name:'Markup Calculator',category:'Business & Money',description:'Work out selling price and markup from your cost.',keywords:['markup','pricing','price'],intent:['pricing','markup']},
 {slug:'margin-calculator',related:['pricing-calculator','profit-calculator','break-even-calculator'],name:'Margin Calculator',category:'Business & Money',description:'Calculate gross margin from cost and selling price.',keywords:['margin','profit','pricing'],intent:['margin','profit']},
 {slug:'break-even-calculator',name:'Break-even Calculator',category:'Business & Money',description:'Find the sales volume needed to cover fixed and variable costs.',keywords:['break even','costs','sales'],intent:['break even','cover costs']},
 {slug:'pricing-calculator',name:'Pricing Calculator',category:'Business & Money',description:'Build a practical selling price from costs and target margin.',keywords:['pricing','price','margin'],intent:['what to charge','price']},
 {slug:'roas-calculator',related:['cac-calculator','profit-calculator','amazon-profit-checker'],name:'ROAS (Return on Ad Spend) Calculator',category:'Advertising',description:'Check whether advertising revenue supports your ad spend.',keywords:['roas','ads','advertising'],intent:['ads','advertising','campaign']},
 {slug:'cac-calculator',name:'CAC (Customer Acquisition Cost) Calculator',category:'Advertising',description:'Estimate customer acquisition cost from marketing spend.',keywords:['cac','customers','ads'],intent:['customer acquisition','marketing']},
 {slug:'hourly-rate-calculator',name:'Freelancer Hourly Rate Calculator',category:'Freelancers',description:'Estimate a sustainable hourly rate from income goals and working time.',keywords:['freelancer','hourly','rate','client'],intent:['freelance','client rate']},
 {slug:'amazon-profit-checker',related:['profit-calculator','margin-calculator','roas-calculator'],name:'Amazon Profitability Checker',category:'E-commerce',description:'Estimate marketplace profit after core costs and fees.',keywords:['amazon','seller','profit','fees'],intent:['amazon','seller','fees']},
 {slug:'cleaning-profit-calculator',related:['cleaning-quote-calculator','cleaning-time-estimator','profit-calculator'],name:'Cleaning Profit Calculator',category:'Cleaning Business',description:'Estimate profit per cleaning job after labor, supplies and travel.',keywords:['cleaning','profit','labor','job'],intent:['cleaning business','cleaning profit']},
 {slug:'cleaning-quote-calculator',related:['cleaning-profit-calculator','cleaning-time-estimator','pricing-calculator'],name:'Cleaning Quote Calculator',category:'Cleaning Business',description:'Create a practical starting quote from job size, time and target margin.',keywords:['cleaning','quote','house cleaning','price'],intent:['cleaning quote','what to charge']},
 {slug:'cleaning-time-estimator',name:'Cleaning Time Estimator',category:'Cleaning Business',description:'Estimate job time using area, condition and service intensity.',keywords:['cleaning','time','labor'],intent:['cleaning time','labor']},
 {slug:'cloud-cost-calculator',name:'Cloud Cost Calculator',category:'Cloud & Tech',description:'Build a simple monthly infrastructure cost estimate.',keywords:['cloud','aws','cost','infrastructure'],intent:['cloud bill','aws cost']},
 {slug:'business-health-check',name:'Business Health Check',category:'Business Operations',description:'A quick diagnostic for pricing, margin, cash flow and customer acquisition.',keywords:['business','health','diagnosis','cash flow'],intent:['business problem','cash flow','business health']},
];
export const categories=[...new Set(tools.map(t=>t.category))];
export function getTool(slug:string){return tools.find(t=>t.slug===slug)}
